server.port=8080

# HTTP UTF-8 Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# Database Configuration
spring.datasource.url=${VAANI_DB_URL:jdbc:h2:file:./data/vaanidb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE}
spring.datasource.username=${VAANI_DB_USERNAME:sa}
spring.datasource.******
spring.datasource.driver-class-name=${VAANI_DB_DRIVER:org.h2.Driver}

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${VAANI_HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.connection.charSet=UTF-8

# Upload File Size Limits
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
